export const red = '#e63b2e'
export const yellow = '#dba159'
export const green = '#16db65'
export const gray = '#c5cbd3'
export const darkGray = '#474647'
export const grayedOut = '#ccc5b9'
export const avatarBlue = '#49c6e5'
// export const backgroundColor = '#f7f7f7'

export const backgroundColor = '#3db3e2'
export const darkerBackgroundColor = '#046488'
export const lighterBackgroundColor = '#bbecec'
export const accentColor = '#a4e76f'
export const oppositeColor = '#FFA23D'
export const darkTextColor = '#422c6f'
export const lightTextColor = '#ffffff'
