# Generated by Django 2.1.2 on 2018-12-09 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.IntegerField(default=0)),
                ('xp', models.IntegerField(default=0)),
                ('stars', models.IntegerField(default=0)),
                ('avatar', models.CharField(max_length=500, null=True)),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.IntegerField(default=0)),
                ('photo', models.CharField(max_length=200)),
                ('color', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('timeGoal', models.IntegerField(default=0)),
                ('timeMax', models.IntegerField(default=0)),
                ('timeMin', models.IntegerField(default=0)),
                ('childID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_manager.Child')),
            ],
        ),
    ]
