# Generated by Django 2.1.2 on 2018-12-13 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=32)),
                ('photo', models.CharField(max_length=256, null=True)),
                ('color', models.CharField(max_length=10)),
                ('weight', models.IntegerField(default=0)),
                ('periodicity', models.CharField(default='1111111', max_length=7)),
                ('isWeeklyRepeatable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('level', models.IntegerField(default=1)),
                ('xp', models.IntegerField(default=0)),
                ('stars', models.IntegerField(default=0)),
                ('avatar', models.CharField(max_length=500, null=True)),
                ('image', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=32)),
                ('photo', models.CharField(max_length=256, null=True)),
                ('color', models.CharField(max_length=10)),
                ('weight', models.IntegerField(default=0)),
                ('periodicity', models.CharField(default='1111111', max_length=7)),
                ('isWeeklyRepeatable', models.BooleanField(default=True)),
                ('childID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_manager.Child')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityProgressType', models.CharField(default='bar', max_length=10)),
                ('activityShowTimer', models.BooleanField(default=False)),
                ('activityFeedback', models.CharField(default='visual', max_length=15)),
                ('feedbackFrequency', models.CharField(default='normal', max_length=15)),
                ('visualStyle', models.CharField(default='cartoon', max_length=15)),
                ('routinePlayType', models.CharField(default='choose', max_length=15)),
                ('playSounds', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_manager.UserInfo'),
        ),
        migrations.AddField(
            model_name='activity',
            name='routineID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_manager.Routine'),
        ),
    ]
