# Generated by Django 2.1.2 on 2018-12-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='isWeeklyRepeatable',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='periodicity',
        ),
        migrations.AddField(
            model_name='activity',
            name='timeGoal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='timeMax',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='timeMin',
            field=models.IntegerField(default=0),
        ),
    ]
