# Generated by Django 2.1.2 on 2018-12-08 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.IntegerField(default=0)),
                ('photo', models.CharField(max_length=200)),
                ('color', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('timeGoal', models.IntegerField(default=0)),
                ('timeMax', models.IntegerField(default=0)),
                ('timeMin', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='child',
            old_name='points',
            new_name='level',
        ),
        migrations.RemoveField(
            model_name='child',
            name='parent',
        ),
        migrations.AddField(
            model_name='child',
            name='avatar',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='child',
            name='xp',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.AddField(
            model_name='routine',
            name='childID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_manager.Child'),
        ),
        migrations.AddField(
            model_name='child',
            name='userID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='routine_manager.User'),
        ),
    ]
