# Generated by Django 2.1.2 on 2018-12-11 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_manager.UserInfo'),
        ),
    ]
