# Generated by Django 2.1.2 on 2018-12-09 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine_manager', '0002_auto_20181208_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='child',
            name='userID',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='child',
            name='parentID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='routine_manager.Parent'),
        ),
    ]
