# Generated by Django 2.1.2 on 2018-12-14 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine_manager', '0002_auto_20181213_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rewardGained', models.IntegerField(default=0)),
                ('elapsedTime', models.IntegerField(default=0)),
                ('timeStamp', models.IntegerField(default=0)),
                ('activityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_manager.Activity')),
                ('childID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_manager.Child')),
            ],
        ),
    ]
