# Generated by Django 2.1.2 on 2018-12-11 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routine_manager', '0003_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='userID',
        ),
        migrations.AddField(
            model_name='settings',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
