# Generated by Django 2.1.4 on 2018-12-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_manager', '0003_activityhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityhistory',
            name='timeStamp',
            field=models.CharField(max_length=500),
        ),
    ]
