# Generated by Django 2.1.2 on 2018-12-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_manager', '0005_auto_20181217_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
