# Generated by Django 2.1.2 on 2018-12-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_manager', '0007_auto_20181211_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='activityProgressType',
            field=models.CharField(default='clock', max_length=10),
        ),
    ]
