# Generated by Django 2.1.2 on 2018-12-11 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine_manager', '0009_auto_20181211_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='user',
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
