# Generated by Django 2.1.2 on 2018-12-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_manager', '0013_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routine',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='timeGoal',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='timeMax',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='timeMin',
        ),
        migrations.AddField(
            model_name='routine',
            name='isWeeklyRepeatable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='periodicity',
            field=models.CharField(default='1111111', max_length=7),
        ),
        migrations.AlterField(
            model_name='routine',
            name='color',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='routine',
            name='image',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='routine',
            name='photo',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
