# Generated by Django 2.1.2 on 2018-12-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_manager', '0014_auto_20181212_0255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routine',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='routine',
            name='photo',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
