# Generated by Django 2.1.2 on 2018-12-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_manager', '0015_auto_20181212_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='isWeeklyRepeatable',
            field=models.BooleanField(default=True),
        ),
    ]
