# Generated by Django 2.1.2 on 2018-12-12 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine_manager', '0016_routine_isweeklyrepeatable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=32)),
                ('photo', models.CharField(max_length=256, null=True)),
                ('color', models.CharField(max_length=10)),
                ('weight', models.IntegerField(default=0)),
                ('timeGoal', models.IntegerField(default=0)),
                ('timeMax', models.IntegerField(default=0)),
                ('timeMin', models.IntegerField(default=0)),
                ('routineID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_manager.Routine')),
            ],
        ),
    ]
