# Generated by Django 2.1.2 on 2018-12-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_manager', '0004_auto_20181215_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='image',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
