# Generated by Django 2.1.2 on 2018-12-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_manager', '0007_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
