/* Generated By:JJTree: Do not edit this line. ASTARR_SIZE.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTARR_SIZE extends SimpleNode {
  public ASTARR_SIZE(int id) {
    super(id);
  }

  public ASTARR_SIZE(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8786c28c20aa23952dbfeed961d5c8c0 (do not edit this line) */
