/* Generated By:JJTree: Do not edit this line. ASTARR_ELEM.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTARR_ELEM extends SimpleNode {
  public ASTARR_ELEM(int id) {
    super(id);
  }

  public ASTARR_ELEM(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bb7b1a3ae9c1544f75bd8cdc4d7812e7 (do not edit this line) */
