/* Generated By:JJTree: Do not edit this line. ASTARR_DECL.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTARR_DECL extends SimpleNode {
  public ASTARR_DECL(int id) {
    super(id);
  }

  public ASTARR_DECL(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=188fb1a220fb4d3e877ee77ce210a904 (do not edit this line) */
