/* Generated By:JJTree: Do not edit this line. ASTARR_ACC.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTARR_ACC extends SimpleNode {
  public ASTARR_ACC(int id) {
    super(id);
  }

  public ASTARR_ACC(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=45c6b58c48735d86d524fd7e36bd78e3 (do not edit this line) */
