/* Generated By:JJTree: Do not edit this line. ASTACC.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTACC extends SimpleNode {
  public ASTACC(int id) {
    super(id);
  }

  public ASTACC(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=300ab79fa563c8f0855c377c06c1556e (do not edit this line) */
