/* Generated By:JJTree: Do not edit this line. ASTARG.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTARG extends SimpleNode {
  public ASTARG(int id) {
    super(id);
  }

  public ASTARG(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=28e3004c6693d6030219335499294ee3 (do not edit this line) */
