/* Generated By:JJTree: Do not edit this line. ASTARG_LIST.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTARG_LIST extends SimpleNode {
  public ASTARG_LIST(int id) {
    super(id);
  }

  public ASTARG_LIST(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4e2bea02085bb8b05abc5dae5c65f661 (do not edit this line) */
