/* Generated By:JJTree: Do not edit this line. ASTASSI.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTASSI extends SimpleNode {
  public ASTASSI(int id) {
    super(id);
  }

  public ASTASSI(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dacdce9f4762ce609294993d16eae64a (do not edit this line) */
