/* Generated By:JJTree: Do not edit this line. ASTCALL.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCALL extends SimpleNode {
  public ASTCALL(int id) {
    super(id);
  }

  public ASTCALL(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d39935f13b113f3e29b04b4e4c8c8ea2 (do not edit this line) */
