/* Generated By:JJTree: Do not edit this line. ASTELEMENT.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTELEMENT extends SimpleNode {
  public ASTELEMENT(int id) {
    super(id);
  }

  public ASTELEMENT(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2cf8a5f81efca79b755caa19ea082eb3 (do not edit this line) */
