/* Generated By:JJTree: Do not edit this line. ASTEXPR_TEST.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEXPR_TEST extends SimpleNode {
  public ASTEXPR_TEST(int id) {
    super(id);
  }

  public ASTEXPR_TEST(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cc5be5eea8e35128c2e4e756e0b785c4 (do not edit this line) */
