/* Generated By:JJTree: Do not edit this line. ASTFunctionAssign.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFunctionAssign extends SimpleNode {
  public ASTFunctionAssign(int id) {
    super(id);
  }

  public ASTFunctionAssign(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=50d48889e360bdc5c6bdaaef11a57747 (do not edit this line) */
