/* Generated By:JJTree: Do not edit this line. ASTFUNCT_ASSI.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFUNCT_ASSI extends SimpleNode {
  public ASTFUNCT_ASSI(int id) {
    super(id);
  }

  public ASTFUNCT_ASSI(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=815cd61957c8f4f38a7bf956fe4cb45e (do not edit this line) */
