/* Generated By:JJTree: Do not edit this line. ASTFUNCTION.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFUNCTION extends SimpleNode {
  public ASTFUNCTION(int id) {
    super(id);
  }

  public ASTFUNCTION(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=67490ed0c4417a1e1fdff455b59ba090 (do not edit this line) */
