/* Generated By:JJTree: Do not edit this line. ASTFUNCT_DECL.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFUNCT_DECL extends SimpleNode {
  public ASTFUNCT_DECL(int id) {
    super(id);
  }

  public ASTFUNCT_DECL(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=930a8c509be3d739248621233472681a (do not edit this line) */
