/* Generated By:JJTree: Do not edit this line. ASTFUNCT_CONT.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFUNCT_CONT extends SimpleNode {
  public ASTFUNCT_CONT(int id) {
    super(id);
  }

  public ASTFUNCT_CONT(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bfb0d9469655c3f611172e239533935d (do not edit this line) */
