/* Generated By:JJTree: Do not edit this line. ASTFUNCT.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFUNCT extends SimpleNode {
  public ASTFUNCT(int id) {
    super(id);
  }

  public ASTFUNCT(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d5b87e766bd91c8bf21ebc97c8036f88 (do not edit this line) */
