/* Generated By:JJTree: Do not edit this line. ASTIND.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIND extends SimpleNode {
  public ASTIND(int id) {
    super(id);
  }

  public ASTIND(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ba16bd02c3608e50c8bbe841d4ca60c1 (do not edit this line) */
