/* Generated By:JJTree: Do not edit this line. ASTMOD.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMOD extends SimpleNode {
  public ASTMOD(int id) {
    super(id);
  }

  public ASTMOD(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=126dfba6bdeb9b3fb49e9eb51911949d (do not edit this line) */
