/* Generated By:JJTree: Do not edit this line. ASTMODULE.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMODULE extends SimpleNode {
  public ASTMODULE(int id) {
    super(id);
  }

  public ASTMODULE(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=12a9056c10ce160b8d32a716e3b3014e (do not edit this line) */
