/* Generated By:JJTree: Do not edit this line. ASTRHS.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTRHS extends SimpleNode {
  public ASTRHS(int id) {
    super(id);
  }

  public ASTRHS(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=87542c8888c0a54476e884a5d1ab21c0 (do not edit this line) */
