/* Generated By:JJTree: Do not edit this line. ASTSTMT_LIST.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSTMT_LIST extends SimpleNode {
  public ASTSTMT_LIST(int id) {
    super(id);
  }

  public ASTSTMT_LIST(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=13c2ed94b3432acd0ab064813d15e2d4 (do not edit this line) */
