/* Generated By:JJTree: Do not edit this line. ASTSCAL_DECL.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSCAL_DECL extends SimpleNode {
  public ASTSCAL_DECL(int id) {
    super(id);
  }

  public ASTSCAL_DECL(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b3d4a654d23f74ca32af77f03f65564b (do not edit this line) */
