/* Generated By:JJTree: Do not edit this line. ASTSTMT.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSTMT extends SimpleNode {
  public ASTSTMT(int id) {
    super(id);
  }

  public ASTSTMT(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=57a36dc832542d4019bffdbc004db831 (do not edit this line) */
