/* Generated By:JJTree: Do not edit this line. ASTSCA_ACC.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSCA_ACC extends SimpleNode {
  public ASTSCA_ACC(int id) {
    super(id);
  }

  public ASTSCA_ACC(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bb53d56a7e34bc3d525776a21939dbe1 (do not edit this line) */
