/* Generated By:JJTree: Do not edit this line. ASTTERM.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTERM extends SimpleNode {
  public ASTTERM(int id) {
    super(id);
  }

  public ASTTERM(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d2a4a1c7cc924e8213e9b1821b4d25e3 (do not edit this line) */
