/* Generated By:JJTree: Do not edit this line. ASTVAR_LIST.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVAR_LIST extends SimpleNode {
  public ASTVAR_LIST(int id) {
    super(id);
  }

  public ASTVAR_LIST(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=43caf81568bc811669eac781c5fc2058 (do not edit this line) */
