/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 6.0_1 */
public interface ParserTreeConstants
{
  public int JJTMODULE = 0;
  public int JJTDECLARATION = 1;
  public int JJTELEMENT = 2;
  public int JJTARRAYELEMENT = 3;
  public int JJTSCALARDECLARATION = 4;
  public int JJTARRAYDECLARATION = 5;
  public int JJTFUNCTION = 6;
  public int JJTFUNCTIONASSIGN = 7;
  public int JJTFUNCTIONDECLARATION = 8;
  public int JJTFUNCTIONCONTENT = 9;
  public int JJTVARLIST = 10;
  public int JJTSTMTLST = 11;
  public int JJTSTMT = 12;
  public int JJTASSIGN = 13;
  public int JJTLHS = 14;
  public int JJTRHS = 15;
  public int JJTARRAYACCESS = 16;
  public int JJTSCALARACCESS = 17;
  public int JJTACCESS = 18;
  public int JJTINDEX = 19;
  public int JJTTERM = 20;
  public int JJTARRAYSIZE = 21;
  public int JJTCALL = 22;
  public int JJTARGUMENTLIST = 23;
  public int JJTARGUMENT = 24;
  public int JJTWHILE = 25;
  public int JJTEXPRTEST = 26;
  public int JJTIF = 27;


  public String[] jjtNodeName = {
    "Module",
    "Declaration",
    "Element",
    "ArrayElement",
    "ScalarDeclaration",
    "ArrayDeclaration",
    "Function",
    "FunctionAssign",
    "FunctionDeclaration",
    "FunctionContent",
    "Varlist",
    "Stmtlst",
    "Stmt",
    "Assign",
    "Lhs",
    "Rhs",
    "ArrayAccess",
    "ScalarAccess",
    "Access",
    "Index",
    "Term",
    "ArraySize",
    "Call",
    "ArgumentList",
    "Argument",
    "While",
    "Exprtest",
    "If",
  };
}
/* JavaCC - OriginalChecksum=f5fe4f82d566250e96bfafa187161e76 (do not edit this line) */
