/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int RELA_OP = 7;
  /** RegularExpression Id. */
  int ADDSUB_OP = 8;
  /** RegularExpression Id. */
  int ARITH_OP = 9;
  /** RegularExpression Id. */
  int BITWISE_OP = 10;
  /** RegularExpression Id. */
  int NOT_OP = 11;
  /** RegularExpression Id. */
  int WHILE = 12;
  /** RegularExpression Id. */
  int IF = 13;
  /** RegularExpression Id. */
  int ELSE = 14;
  /** RegularExpression Id. */
  int ASSIGN = 15;
  /** RegularExpression Id. */
  int ASPA = 16;
  /** RegularExpression Id. */
  int LPAR = 17;
  /** RegularExpression Id. */
  int RPAR = 18;
  /** RegularExpression Id. */
  int VIRG = 19;
  /** RegularExpression Id. */
  int PVIRG = 20;
  /** RegularExpression Id. */
  int LCHAVETA = 21;
  /** RegularExpression Id. */
  int RCHAVETA = 22;
  /** RegularExpression Id. */
  int FUNCTION = 23;
  /** RegularExpression Id. */
  int MODULE = 24;
  /** RegularExpression Id. */
  int SIZE = 25;
  /** RegularExpression Id. */
  int INTEGER = 26;
  /** RegularExpression Id. */
  int ID = 27;
  /** RegularExpression Id. */
  int LETTER = 28;
  /** RegularExpression Id. */
  int DIGIT = 29;
  /** RegularExpression Id. */
  int STRING = 30;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<RELA_OP>",
    "<ADDSUB_OP>",
    "<ARITH_OP>",
    "<BITWISE_OP>",
    "\"!\"",
    "\"while\"",
    "\"if\"",
    "\"else\"",
    "\"=\"",
    "\"\\\"\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"function\"",
    "\"module\"",
    "\"size\"",
    "<INTEGER>",
    "<ID>",
    "<LETTER>",
    "<DIGIT>",
    "<STRING>",
    "\"[\"",
    "\"]\"",
    "\".\"",
  };

}
